apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: retrodep-pgca
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: retrodep-pgca
    app.kubernetes.io/part-of: test-app-881
  name: retrodep-pgca
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-retrodep
      app.kubernetes.io/instance: retrodep-pgca
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-retrodep
        app.kubernetes.io/instance: retrodep-pgca
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-881/retrodep-pgca@sha256:9aaaad52d69a0be7d86cc53d10477f34d82ad5b8eb1faa362f6f18ec0f11dab8
        name: my-retrodep
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
