apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: e2e-tests-parent-image-with-digest-only-dvfw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: e2e-tests-parent-image-with-digest-only-dvfw
    app.kubernetes.io/part-of: test-app-881
  name: e2e-tests-parent-image-with-digest-only-dvfw
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: e2e-tests-parent-image-with-digest-only-dvfw
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: e2e-tests-parent-image-with-digest-only-dvfw
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-881/e2e-tests-parent-image-with-digest-only-dvfw@sha256:4d990696c1d47007b8168c5ce80d6f1ac5db5bba865b082e37f0e32bff1ed71b
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8081
        resources: {}
status: {}
