apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: pip-e2e-test-rahn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pip-e2e-test-rahn
    app.kubernetes.io/part-of: test-app-881
  name: pip-e2e-test-rahn
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: pip-e2e-test
      app.kubernetes.io/instance: pip-e2e-test-rahn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pip-e2e-test
        app.kubernetes.io/instance: pip-e2e-test-rahn
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-881/pip-e2e-test-rahn@sha256:038b7f07e4dcb23bbadd1210ae6c740e21f2404263d1d73eaa4ac497ba6af0c7
        name: pip-e2e-test
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
