apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fbc-sample-repo-bqvu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fbc-sample-repo-bqvu
    app.kubernetes.io/part-of: test-app-881
  name: fbc-sample-repo-bqvu
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: fbc
      app.kubernetes.io/instance: fbc-sample-repo-bqvu
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fbc
        app.kubernetes.io/instance: fbc-sample-repo-bqvu
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-881/fbc-sample-repo-bqvu@sha256:be98f5ebed6096253f454131a67a0ca2a1c33622a8846242e43a0308ce352698
        name: fbc
        ports:
        - containerPort: 50051
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi
status: {}
