apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: e2e-tests-use-latest-parent-image-jdux
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: e2e-tests-use-latest-parent-image-jdux
    app.kubernetes.io/part-of: test-app-881
  name: e2e-tests-use-latest-parent-image-jdux
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: e2e-tests-use-latest-parent-image-jdux
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: e2e-tests-use-latest-parent-image-jdux
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-881/e2e-tests-use-latest-parent-image-jdux@sha256:d722a13fe7e613a1475f76be913aa3435b6ea1ea5a55e774978bcfbbaf4fc2e9
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8081
        resources: {}
status: {}
