apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: maven-hello-world-uzqs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: maven-hello-world-uzqs
    app.kubernetes.io/part-of: test-app-881
  name: maven-hello-world-uzqs
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: maven-hello-world-uzqs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: maven-hello-world-uzqs
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-881/maven-hello-world-uzqs@sha256:2b877556028d0488fe34c665b90d4c0562ffd4f716837af936d38ea8abcc3dae
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
